CREATE TABLE Job_Applications (
    application_id INT AUTO_INCREMENT PRIMARY KEY,
    job_id INT NOT NULL,
    job_seeker_id INT NOT NULL,
    resume MEDIUMBLOB,
    experience VARCHAR(100),
    work_authorization ENUM('US_CITIZEN', 'GREEN_CARD', 'H1B', 'OPT', 'OTHER') NOT NULL,
    status ENUM('PENDING', 'SHORTLISTED', 'HIRED', 'INTERVIEWED', 'REJECTED') DEFAULT 'PENDING',
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

